apiVersion: v1
kind: Pod
metadata:
  name: workshop
spec:
  containers:
    - env:
      - name: HF_TOKEN
        value: "<your huggingface token>"
      name: workshop
      image: gcr.io/chai-959f8/val-corner/pod-image:latest
      command: ['sleep']
      args: ['infinity']
      resources:
        limits:
          cpu: "2"
          memory: 64Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 64Gi
          nvidia.com/gpu: "1"
      imagePullPolicy: Always
  imagePullSecrets:
    - name: docker-creds
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - A100_NVLINK_80GB
